version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      .env

volumes:
  postgres_data: