# Generated by Django 3.0 on 2022-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220627_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='text',
            field=models.TextField(max_length=900),
        ),
    ]
